//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.AddressService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddressService.cidadesSoap")]
    internal interface cidadesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_ESTADOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RETORNA_ESTADOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_ESTADOS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_ESTADOSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADES_ESTADO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RETORNA_CIDADES_ESTADO(string ESTADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADES_ESTADO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADES_ESTADOAsync(string ESTADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RETORNA_CIDADES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADES", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADESAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADES_FILTRO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RETORNA_CIDADES_FILTRO(string ESTADO, string NOME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADES_FILTRO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADES_FILTROAsync(string ESTADO, string NOME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADE_ESPECIFICA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RETORNA_CIDADE_ESPECIFICA(int COD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADE_ESPECIFICA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADE_ESPECIFICAAsync(int COD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_ESTADO_ESPECIFICO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RETORNA_ESTADO_ESPECIFICO(int COD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_ESTADO_ESPECIFICO", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RETORNA_ESTADO_ESPECIFICOAsync(int COD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADE_CEP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RETORNA_CIDADE_CEP(string CEP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RETORNA_CIDADE_CEP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADE_CEPAsync(string CEP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface cidadesSoapChannel : Negocio.AddressService.cidadesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class cidadesSoapClient : System.ServiceModel.ClientBase<Negocio.AddressService.cidadesSoap>, Negocio.AddressService.cidadesSoap {
        
        public cidadesSoapClient() {
        }
        
        public cidadesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cidadesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cidadesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cidadesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet RETORNA_ESTADOS() {
            return base.Channel.RETORNA_ESTADOS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_ESTADOSAsync() {
            return base.Channel.RETORNA_ESTADOSAsync();
        }
        
        public System.Data.DataSet RETORNA_CIDADES_ESTADO(string ESTADO) {
            return base.Channel.RETORNA_CIDADES_ESTADO(ESTADO);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADES_ESTADOAsync(string ESTADO) {
            return base.Channel.RETORNA_CIDADES_ESTADOAsync(ESTADO);
        }
        
        public System.Data.DataSet RETORNA_CIDADES() {
            return base.Channel.RETORNA_CIDADES();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADESAsync() {
            return base.Channel.RETORNA_CIDADESAsync();
        }
        
        public System.Data.DataSet RETORNA_CIDADES_FILTRO(string ESTADO, string NOME) {
            return base.Channel.RETORNA_CIDADES_FILTRO(ESTADO, NOME);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADES_FILTROAsync(string ESTADO, string NOME) {
            return base.Channel.RETORNA_CIDADES_FILTROAsync(ESTADO, NOME);
        }
        
        public System.Data.DataSet RETORNA_CIDADE_ESPECIFICA(int COD) {
            return base.Channel.RETORNA_CIDADE_ESPECIFICA(COD);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADE_ESPECIFICAAsync(int COD) {
            return base.Channel.RETORNA_CIDADE_ESPECIFICAAsync(COD);
        }
        
        public string RETORNA_ESTADO_ESPECIFICO(int COD) {
            return base.Channel.RETORNA_ESTADO_ESPECIFICO(COD);
        }
        
        public System.Threading.Tasks.Task<string> RETORNA_ESTADO_ESPECIFICOAsync(int COD) {
            return base.Channel.RETORNA_ESTADO_ESPECIFICOAsync(COD);
        }
        
        public System.Data.DataSet RETORNA_CIDADE_CEP(string CEP) {
            return base.Channel.RETORNA_CIDADE_CEP(CEP);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RETORNA_CIDADE_CEPAsync(string CEP) {
            return base.Channel.RETORNA_CIDADE_CEPAsync(CEP);
        }
    }
}
